### ISSUE TITLE
Scope of this project

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-backend#14]
What is this project doing?
I see it mentions .NET, MSSQL, as Node JS, Yarn and Angular CLI, shouldn't the 'frontend' for care workers be in another project?

My advise to make this more accessible for other developer :eyes:
- [ ] Update `README.md` with folder overview plus short summary
- [ ] Put `README.md` in every folder with the project/folder description what this thing is doing.

**Comment by ijansch** [comment]
Agreed, this contains both the backend and a portal. This ideally is split into separate repositories.

**Comment by ijansch** [comment]
Separate repositories have been requested.

**Comment by hiddehs** [comment]
> Update README.md with folder overview plus short summary

Agreed and we are definitely working on clarifying the solution architecture .md doc of the back-end, we've already structured the [solution file (take a look with your IDE)](https://github.com/minvws/nl-covid19-notification-app-backend/blob/master/ExposureNotification.Backend.sln) in the upcoming version – will be synced asap. For now I'll refer to [nl-covid19-notification-app-coordination](https://github.com/minvws/nl-covid19-notification-app-coordination) as a source of truth.

**Comment by ryanbnl** [comment]
The GGD portal code has been moved to its own repository (https://github.com/minvws/nl-covid19-notification-app-iccportal) so I will close this ticket.

In the coming time we will be improving the documentation around the software architecture and documentation of the backend.
