### ISSUE TITLE
Developer level connection strings/credentials should be generated

### ISSUE THREAD

**Issue by fgheysels** [minvws/nl-covid19-notification-app-backend#15]
Some files in this repository contain secrets.  I don't think you want to expose `sa` db - passwords to the whole world. 

For instance [here](https://github.com/minvws/nl-covid19-notification-app-backend/blob/master/docker/docker-compose.yml) and [here](https://github.com/minvws/nl-covid19-notification-app-backend/blob/master/docker/standalone/appsettings.Development.json).  (You should also not add an appsettings.development.json file in source-control).

Make use of docker secrets to inject secrets in a container; do not expose connectionstrings via the git repository!

**Comment by hugopilot** [comment]
Another secret found [here](https://github.com/minvws/nl-covid19-notification-app-backend/blob/d987f979130111d8d6f7725a89a73ac37da8a3b2/ICCPortal/appsettings.json#L18)

**Comment by ijansch** [comment]
Thanks for keeping an eye on this! The docker setup is intended to be a standalone server for development purposes, so making sure the components can talk to each other is intentional. In production setups such secrets will be provided through configuration management. 

I’ll ask the team to verify, just in case, and add comments where applicable.

**Comment by ryanbnl** [comment]
The passwords in docker, the appsettings.Development.json and in the angular environments are all development settings. The production settings are stored in another system which the developers don't have access to :)

**Comment by ryanbnl** [comment]
I can't speak for the other developers but my local settings are totally different from the settings we've provided for the docker deployment.

**Comment by fgheysels** [comment]
To be blunt, I think it is a very bad practice to put things like connectionstrings (even if they're development settings) in a git repo.  

I believe this has just been done for ease of use, so that every developer is directly up to speed without having to setup some kind of configuration, but there are better ways to tackle this imo.   Secrets can be stored by the ASP.NET SecretManager or in a centralized secure secret store.    I think no shortcuts should be taken on security in favor of ease-of-use; especially for a government backed application who's source code is publicly available.   But these are just my 2 cents :)

**Comment by Naamloos** [comment]
again? 😳

**Comment by hugopilot** [comment]
To add to this. This is not the first time secrets are 'leaked' (#7). Even though they are not used in production, you don't want people to think you're not handling keys/secrets like amateurs (referring to [this](https://nos.nl/artikel/2336416-lek-in-rivm-coronasite-gegevens-van-gebruikers-makkelijk-in-te-zien.html)).

**Comment by ijansch** [comment]
Comparing this to an actual data leak is apples and oranges, but point taken. The same fix as for #7 could probably be applied here. I’ll leave this open for now. Given that it’s a process improvement / best practice and not an actual leak, I’ll adjust the title to ‘developer level connection strings should be generated’. Agreed?

**Comment by hiddehs** [comment]
> To be blunt, I think it is a very bad practice to put things like connectionstrings (even if they're development settings) in a git repo.
> 
> I believe this has just been done for ease of use, so that every developer is directly up to speed without having to setup some kind of configuration, but there are better ways to tackle this imo. Secrets can be stored by the ASP.NET SecretManager or in a centralized secure secret store. I think no shortcuts should be taken on security in favor of ease-of-use; especially for a government backed application who's source code is publicly available. But these are just my 2 cents :)

Agreed and we've clarified the `README.md` for local quickstart development docker usage only in the upcoming sync. But I love to see your contributions on this point, do not hesitate to make a PR to improve the local docker development secrets. Keep in mind that we still want to enable app developers and testers to quickly start the latest version of the Standalone Server via [docker](https://github.com/minvws/nl-covid19-notification-app-backend/blob/master/docker/docker-compose.yml) without having to fuzzle with all different configs.

**Comment by ryanbnl** [comment]
This was resolved a couple of months ago, so I'm closing the ticket.
