### ISSUE TITLE
2020-08-19: [VWS/Covid19NotificationApp]

### ISSUE THREAD

**Issue by mrquincle** [minvws/nl-covid19-notification-app-backend#22]
### Describe the bug, issue or concern

The concern is the existence of the code block in https://github.com/minvws/nl-covid19-notification-app-backend/blob/master/Components/Icc/Models/TheIdentityHubClaimTypes.cs:

```

        internal const string AccessToken = "http://schemas.u2uconsult.com/ws/2014/03/identity/claims/accesstoken";
        internal const string AuthenticationStrength = "http://schemas.u2uconsult.com/ws/2016/08/identity/claims/authenticationstrength";
        internal const string ClientId = "http://schemas.u2uconsult.com/ws/2014/11/identity/claims/clientid";
        internal const string OldIdentityId = "http://schemas.u2uconsult.com/ws/2019/02/identity/claims/oldidentityid";
        internal const string DisplayName = "http://schemas.u2uconsult.com/ws/2014/04/identity/claims/displayname";
        internal const string EmailAddress = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress";
        internal const string EmailAddressVerified = "http://schemas.u2uconsult.com/ws/2017/02/identity/claims/emailaddressverified";
        internal const string GivenName = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname";
        internal const string IdentityProvider = "http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider";
        internal const string LargePicture = "http://schemas.u2uconsult.com/ws/2014/04/identity/claims/largepicture";
        internal const string MediumPicture = "http://schemas.u2uconsult.com/ws/2014/04/identity/claims/mediumpicture";
        internal const string Scope = "http://schemas.u2uconsult.com/ws/2014/03/identity/claims/scope";
        internal const string SmallPicture = "http://schemas.u2uconsult.com/ws/2014/04/identity/claims/smallpicture";
        internal const string Surname = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname";
        internal static readonly string NameIdentifier = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier";
```

I'm assuming these are either not used or they are used to indicate URLs to third-parties that can be used to establish the validity of the schemes. However, I haven't looked into it. Reasons to remove this:

* These are SEO links for Google to boost the http://u2uconsult.com site (this one as well :-) ).
* These are http links rather than https links, so vulnerable for man in the middle attacks.
* The corresponding server get hits from the system verifying their schemas. This leaks information on use.
* Most of those links do not currently resolve.

### Expected behavior

Fix. Https links to your own backend or remove.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ryanbnl** [comment]
Thanks for the feedback. We will remove the unused codes in the next update.

The URIs are use for schema validation, they are never hit during execution of the code. More importantly, it is impossible to hit the code because this component runs on a machine which has no outbound internet access.

The URLs are never published anywhere so there is no SEO benefit for u2uconsult.com from coronamelder.nl :-)

**Comment by mrquincle** [comment]
Perfect. There's still SEO benefit because the links are on github. ;-)

**Comment by ryanbnl** [comment]
True, but that is tiny and they're part of the identity solution required by the GGDs :)

**Comment by hiddehs** [comment]
@mrquincle please check the usage of `TheIdentityHubClaims` in `Components/Icc/AuthHandlers/JwtService.cs:66`

We do a match on the exact scheme urls in the claims that are received, so changing http to https will break the authentication flow.

For further reference; see `System.Security.Claims.ClaimTypes` where on `12` the base ClaimTypeNamespace is defined.
