### ISSUE TITLE
Decoy probability constant

### ISSUE THREAD

**Issue by jorants** [minvws/nl-covid19-notification-app-backend#24]
### Describe the bug, issue or concern

According to the design documentation the decoy probability should change depending on positive test numbers (and possibly install counts). However, it seems to be fixed to 0.00118, also on the production CDN.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ryanbnl** [comment]
The decoy probability for the apps is regularly reviewed and modified as required. The configuration contained in this repository is only an example, so I am closing the ticket.
