### ISSUE TITLE
Using docker-compose fails

### ISSUE THREAD

**Issue by llewelld** [minvws/nl-covid19-notification-app-backend#25]
### Describe the bug, issue or concern

Currently `docker-compose up --build` fails on a clean clone due to a couple of errors in the Docker file.

This is running on Ubuntu 20.04.

### To Reproduce

1. Create a fresh clone of the repository:
```
git clone https://github.com/minvws/nl-covid19-notification-app-backend.git
```
2. Enter the freshly created repository.
```
cd nl-covid19-notification-app-backend
```
3. Start the docker compose process as described in the docs.
```
cd docker
docker-compose up --build
```
4. Generates the following output and error.

```
$ docker-compose up --build
Building mobile_api
Step 1/23 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS builder
 ---> 656495ef4e20
Step 2/23 : COPY . app/
 ---> Using cache
 ---> c642901eb776
Step 3/23 : WORKDIR app/
 ---> Using cache
 ---> 1ace1d52bf4c
Step 4/23 : COPY docker/development/appsettings.json .
 ---> Using cache
 ---> 88648b988891
Step 5/23 : RUN rm Components/Framework/WindowsIdentityStuff.cs
 ---> Running in d0d719382673
rm: can't remove 'Components/Framework/WindowsIdentityStuff.cs': No such file or directory
ERROR: Service 'mobile_api' failed to build: The command '/bin/sh -c rm Components/Framework/WindowsIdentityStuff.cs' returned a non-zero code: 1
```
5. Fixing this error generates further output leading to another error:

```
MSBUILD : error MSB1009: Project file does not exist.
Switch: DbFillExampleContent/DbFillExampleContent.csproj
ERROR: Service 'mobile_api' failed to build: The command '/bin/sh -c dotnet publish DbFillExampleContent/DbFillExampleContent.csproj --no-self-contained  --configuration Release -o publish/Tools/DbFillExampleContent --version-suffix local' returned a non-zero code: 1
```

### Expected behavior

The docker containers are successfully brought up.

### Screenshots
n/a, see console output above

### Additional context

I'll shortly submit a simple PR to address the issues.

### Governance
- [ x ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ x ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by skos001** [comment]
@llewelld a belated thanks for opening this issue back in 2020 🙌 and sincere apologies that we haven't responded to this pull request all this time 😅 

The Docker setup within the project has changed since your reporting of this issue, and should now work without issue on Windows, Linux and macOS (excepting macOS M1, which has specific work-around instructions in the README).

If the changes to the project solve your original issue, feel free to close this issue and the corresponding pull request 🙂

**Comment by skos001** [comment]
Closing old issue.
