### ISSUE TITLE
Please spell PostgreSQL correctly in the README

### ISSUE THREAD

**Issue by kdekooter** [minvws/nl-covid19-notification-app-backend#3]
It hurts when the name of the world's most awesomest database is mangled like this.

**Comment by tobyhinloopen** [comment]
https://github.com/minvws/nl-covid19-notification-app-backend/pull/4

Happy?

**Comment by kdekooter** [comment]
Nice! Approved them twice :-).

**Comment by rkops-bd** [comment]
We discontinued the support for PostgreSQL. The docker image is configured with MSSQL.

**Comment by kdekooter** [comment]
So much for open source tools...

**Comment by kdekooter** [comment]
So much for open-source...

**Comment by tobyhinloopen** [comment]
I'm just happy the app(s) are on Github! A great step towards better national software.

**Comment by kdekooter** [comment]
Sure, that is a great thing. I just don't understand why any dev would pick SQL Server when Postgres is a option. Would save you a lot of headaches!

**Comment by tobyhinloopen** [comment]
I never had any headaches with using SQL Server, PostgreSQL, MySQL or SQLite. They're all just fine. Just use whatever you're most experienced with, I suppose.

I suppose SQL Server plays nicely with C#/.NET?

**Comment by kdekooter** [comment]
DX issues aside, as a citizen I don't feel comfortable knowing that my data might end up in a proprietary database.

**Comment by tobyhinloopen** [comment]
Where does that stop? Do you want to drop C#/.NET too? What about the server it's running in? I suppose you also don't want it to be using a proprietary OS, so that leaves Linux ("but who's using that, right?") with only open-source drivers.

Next the software needs to run on some kind of hardware. You can't use a proprietary cloud, so let's put a server in a rack somewhere. Oh, Intel and AMD server CPUs aren't open source either. That's not nice.

**Comment by kdekooter** [comment]
I had high hopes for all of this stuff to be open and transparent. But step by step things appear not to be so open...

**Comment by bwbroersma** [comment]
> We discontinued the support for PostgreSQL. The docker image is configured with MSSQL.

@rkops-bd Can you elaborate on this decision? Maybe if you share the issues, the community can either better understand, or help with a solution.

**Comment by jellelicht** [comment]
@rkops-bd any chance you could elaborate a bit on why y'all decided to move database implementations in the end?

**Comment by dirkx** [comment]
As we get closer to production the focus changes. 

For this we're relying on the 247x ops of the Belasting dienst, existing dual DC environment, Security Operations Centres, monitoring, backups, etc, etc.

In that environment it is MS SQL Server that is the norm. And our timelines/priorities dictate that we go as fast as we can; so re-training and retooling 24x7 staff in PostgreSQL, getting that monitored, etc, is simply too much risk.

So while it served us well during dev, field and test - it is no longer important as we go life.

However - we'll try to accept patches if people want to keep things compatible. But for now - getting in production & dealing with Covid is our priority.

**Comment by jellelicht** [comment]
If "speed" was the major concern, you would've found a way to do more the work out in the open :wink: . That _predictable_ speed + legal compliance trump over some perceived purity/ideological shenanigans is completely understandable though. Thank you for your explanation @dirkx , it would have been nice to have something of the sorts shared at the same time as the decision.

**Comment by marekq** [comment]
So you now need Windows Server and MSSQL licenses to deploy this - because it's easier for a few select individuals. We end up with a static, old school infrastructure that requires expensive commercial licenses and isn't easy to port to OSS.

**Comment by jellelicht** [comment]
BD no longer in the picture as far as I understand it, so please reconsider this decision, or explain why it would still be the most strategic choice to stick with MSSQL for now.
