### ISSUE TITLE
remove the private key from the repository

### ISSUE THREAD

**Issue by paulovitorbal** [minvws/nl-covid19-notification-app-backend#5]
https://github.com/minvws/nl-covid19-notification-app-backend/blob/ba0938c3b37c9debed16de80f4206f45033d7021/Components/Services/Signing/HardCodedExposureKeySetSigning.cs

**Comment by mMeijden** [comment]
and maybe a quite obvious suggestion to create a new one now it's available in the history

**Comment by devvoh** [comment]
But the app's going to be totally secure, you guys!

**Comment by ijansch** [comment]
It’s not a real key. Production keys won’t be in source code, but injected through a secure mechanism so that development team doesn’t need to know production secrets. This class is used for local development only.
