### ISSUE TITLE
Private key visible inside the sources

### ISSUE THREAD

**Issue by wmeints** [minvws/nl-covid19-notification-app-backend#7]
https://github.com/minvws/nl-covid19-notification-app-backend/blob/ba0938c3b37c9debed16de80f4206f45033d7021/Components/Services/Signing/HardCodedExposureKeySetSigning.cs#L26

I don't think you want your private key visible like that. Best remove it quickly and regenerate. 
It gives me the creeps to see stuff like this in a code base.

Also, I see you're not working with a process to handle security issues like this one.
Would be nice to have that in place too.

**Comment by wmeints** [comment]
Note, I can see why you did this, but it still looks kinda bad. Wouldn't it be better to generate a key locally and use that instead?

**Comment by rkops-bd** [comment]
To avoid possible confusion, the private key has been removed and is now being generated. To be clear, this key has never been and will never be used on production environments. As the name of the class also indicates, it is hardcoded.

HSMs will be used in production environments, thus ensuring security.
