### ISSUE TITLE
Consider serving a security.txt file

### ISSUE THREAD

**Issue by nicwortel** [minvws/nl-covid19-notification-app-backend#8]
First of all I would like to say that I really appreciate that this work is being open sourced.

I want to propose adding a `security.txt` file to be publicly served by this application.
[security.txt](https://securitytxt.org/) is a proposed standard for listing responsible disclosure policies and contact information. Its purpose is to provide a standard location so security researchers can easily get in contact to report a security issue. The standard is currently in [draft stage](https://tools.ietf.org/html/draft-foudil-securitytxt) but is already in use by organizations like [Google](https://www.google.com/.well-known/security.txt) and [GitHub](https://github.com/.well-known/security.txt).

This GitHub repository already has a [security policy](https://github.com/minvws/nl-covid19-notification-app-backend/security/policy), but once this application is running in production a security researcher who has found a vulnerability might not be aware of the fact that this repository is publicly visible. They will have to search for out-of-band information in order to responsibly disclose security issues. As explained for example by security researcher Troy Hunt, who runs the popular data breach notification service [Have I Been Pwned?](https://haveibeenpwned.com/), [the `security.txt` file is one of the first things he will look for when he tries to contact an organization about a data breach](https://www.troyhunt.com/streamlining-data-breach-disclosures-a-step-by-step-process/). 
Given the high public profile of this application and the focus on privacy and security I believe it is a good step to serve this file, and it comes at no real cost.

Based on the existing security policy published on GitHub, the contents of `security.txt` could look like this:

```
Contact: https://www.ncsc.nl/contact/kwetsbaarheid-melden
Contact: https://english.ncsc.nl/contact/reporting-a-vulnerability-cvd
Encryption: https://english.ncsc.nl/contact/pgp-key
Policy: https://github.com/minvws/nl-covid19-notification-app-backend/security/policy
```

This file should be served from `/.well-known/security.txt` ([RFC8615](https://tools.ietf.org/html/rfc8615)). Other fields, such as `Acknowledgments`, `Canonical` and `Preferred-Languages` are also supported. Please refer to the draft standard or to https://securitytxt.org/ for the full specification.

I would be happy to create a pull request, but I'm not sure where to create this file in order for it to be served as a static file in the document root. If I'm understanding correctly the Docker configuration and `ServerStandAlone` directory are only used for development, and will not be used in production. Alternatively the file could be stored in the root of the repository (as suggested on https://securitytxt.org/) and be be copied to the right location during build-time. As I said, if someone can point me in the right direction I would happily create a pull request for this.

**Comment by nicwortel** [comment]
On a slightly separate note, the `SECURITY.md` file used throughout the @minvws GitHub repositories states:

> ## Please do the following:
> 
> Submit your findings by using the following URL: https://github.com/minvws/nl-covid19-notification-app-coordination/security
> 
> or (...)

The linked URL, however, does not provide an option to report an issue. It only links back to the same policy (see attached screenshot). I therefor believe that https://www.ncsc.nl/contact/kwetsbaarheid-melden is the only way to report security issues, and the first link only adds confusion, unless I'm missing something. It might be a good idea to remove the link to the GitHub security page and instead add a link to the English version of the contact page on ncsc.nl: https://english.ncsc.nl/contact/reporting-a-vulnerability-cvd.

![afbeelding](https://user-images.githubusercontent.com/1055691/84388950-add55d00-abf5-11ea-9946-725612cbe4fe.png)

(I don't have any security issue to report by the way, I was just curious to look into the security policy)

**Comment by ijansch** [comment]
Good points! @dirkx can you have a look at this? I think the suggestion to include a security.txt is a good one, and the other suggestions we should probably look at too.

**Comment by dirkx** [comment]
So I'll keep this open - until we have a website or similar where this makes sense. And will make track that the app its about window has something similar.

**Comment by ChrisvanChip** [comment]
> Good idea. Not a priority - as there is already a 'kwetsbaarheid melden' entry on every page at this time.

But keep the chance of it being overlooked in mind. The security.txt is a globally handled standard.

**Comment by skos001** [comment]
@nicwortel it's been a while since you opened this issue, but nonetheless: it looks like https://coronamelder.nl/.well-known/security.txt is now serving a security.txt file. As such, please feel free to close this issue if that solves this issue 😊

**Comment by skos001** [comment]
Closing old issue.
